export type FarmerSeedReportRow = {
  id: string;
  farmerId: string;
  farmerName: string;
  farmerAddress: string;
  accountNumber: number | null;
  gatePassNo: number;
  invoiceNumber: string;
  date: string;
  variety: string;
  generation: string;
  bag35to40: number;
  bag35to40Rate: number;
  bag35to40Acres: number;
  bag40to45: number;
  bag40to45Rate: number;
  bag40to45Acres: number;
  bag40to50: number;
  bag40to50Rate: number;
  bag40to50Acres: number;
  bag45to50: number;
  bag45to50Rate: number;
  bag45to50Acres: number;
  bag50to55: number;
  bag50to55Rate: number;
  bag50to55Acres: number;
  totalBags: number;
  totalAcres: number;
  averageRate: number;
  totalAmount: number;
  remarks: string;
  createdAt: string;
  updatedAt: string;
};
