/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZustandIndexRouteImport } from './routes/zustand/index'
import { Route as StoreAdminAuthenticatedRouteImport } from './routes/store-admin/_authenticated'
import { Route as StoreAdminLoginIndexRouteImport } from './routes/store-admin/login/index'
import { Route as StoreAdminAuthenticatedAnalyticsRouteRouteImport } from './routes/store-admin/_authenticated/analytics/route'
import { Route as StoreAdminAuthenticatedStorageGatePassIndexRouteImport } from './routes/store-admin/_authenticated/storage-gate-pass/index'
import { Route as StoreAdminAuthenticatedSettingsIndexRouteImport } from './routes/store-admin/_authenticated/settings/index'
import { Route as StoreAdminAuthenticatedPeopleIndexRouteImport } from './routes/store-admin/_authenticated/people/index'
import { Route as StoreAdminAuthenticatedNikasiGatePassIndexRouteImport } from './routes/store-admin/_authenticated/nikasi-gate-pass/index'
import { Route as StoreAdminAuthenticatedIncomingGatePassIndexRouteImport } from './routes/store-admin/_authenticated/incoming-gate-pass/index'
import { Route as StoreAdminAuthenticatedGradingGatePassIndexRouteImport } from './routes/store-admin/_authenticated/grading-gate-pass/index'
import { Route as StoreAdminAuthenticatedFarmerSeedGatePassIndexRouteImport } from './routes/store-admin/_authenticated/farmer-seed-gate-pass/index'
import { Route as StoreAdminAuthenticatedDaybookIndexRouteImport } from './routes/store-admin/_authenticated/daybook/index'
import { Route as StoreAdminAuthenticatedContractTestIndexRouteImport } from './routes/store-admin/_authenticated/contract-test/index'
import { Route as StoreAdminAuthenticatedAnalyticsIndexRouteImport } from './routes/store-admin/_authenticated/analytics/index'
import { Route as StoreAdminAuthenticatedStorageGatePassHistoryIndexRouteImport } from './routes/store-admin/_authenticated/storage-gate-pass/history/index'
import { Route as StoreAdminAuthenticatedStorageGatePassEditIndexRouteImport } from './routes/store-admin/_authenticated/storage-gate-pass/edit/index'
import { Route as StoreAdminAuthenticatedSettingsRbacIndexRouteImport } from './routes/store-admin/_authenticated/settings/rbac/index'
import { Route as StoreAdminAuthenticatedSettingsPreferencesIndexRouteImport } from './routes/store-admin/_authenticated/settings/preferences/index'
import { Route as StoreAdminAuthenticatedSettingsMasterIndexRouteImport } from './routes/store-admin/_authenticated/settings/master/index'
import { Route as StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport } from './routes/store-admin/_authenticated/people/$farmerStorageLinkId/index'
import { Route as StoreAdminAuthenticatedNikasiGatePassHistoryIndexRouteImport } from './routes/store-admin/_authenticated/nikasi-gate-pass/history/index'
import { Route as StoreAdminAuthenticatedNikasiGatePassEditIndexRouteImport } from './routes/store-admin/_authenticated/nikasi-gate-pass/edit/index'
import { Route as StoreAdminAuthenticatedIncomingGatePassHistoryIndexRouteImport } from './routes/store-admin/_authenticated/incoming-gate-pass/history/index'
import { Route as StoreAdminAuthenticatedIncomingGatePassEditIndexRouteImport } from './routes/store-admin/_authenticated/incoming-gate-pass/edit/index'
import { Route as StoreAdminAuthenticatedGradingGatePassHistoryIndexRouteImport } from './routes/store-admin/_authenticated/grading-gate-pass/history/index'
import { Route as StoreAdminAuthenticatedGradingGatePassEditIndexRouteImport } from './routes/store-admin/_authenticated/grading-gate-pass/edit/index'
import { Route as StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRouteImport } from './routes/store-admin/_authenticated/farmer-seed-gate-pass/history/index'
import { Route as StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRouteImport } from './routes/store-admin/_authenticated/farmer-seed-gate-pass/edit/index'
import { Route as StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRouteImport } from './routes/store-admin/_authenticated/analytics/area-breakdown/index'
import { Route as StoreAdminAuthenticatedSettingsMasterStationsIndexRouteImport } from './routes/store-admin/_authenticated/settings/master/stations/index'
import { Route as StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRouteImport } from './routes/store-admin/_authenticated/people/dispatch-ledger/$id/index'
import { Route as StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRouteImport } from './routes/store-admin/_authenticated/people/$farmerStorageLinkId/finance-report/index'
import { Route as StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRouteImport } from './routes/store-admin/_authenticated/people/$farmerStorageLinkId/farmer-report/index'
import { Route as StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRouteImport } from './routes/store-admin/_authenticated/people/$farmerStorageLinkId/accounting-report/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/ungraded/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsStorageIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/storage/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsShedIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/shed/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/incoming/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsGradingIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/grading/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/farmer-seed/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/dispatch-pre-storage/index'
import { Route as StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRouteImport } from './routes/store-admin/_authenticated/analytics/reports/contract-farming/index'
import { Route as StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRouteImport } from './routes/store-admin/_authenticated/people/dispatch-ledger/$id/dispatch-ledger-report/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZustandIndexRoute = ZustandIndexRouteImport.update({
  id: '/zustand/',
  path: '/zustand/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminAuthenticatedRoute = StoreAdminAuthenticatedRouteImport.update({
  id: '/store-admin/_authenticated',
  path: '/store-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminLoginIndexRoute = StoreAdminLoginIndexRouteImport.update({
  id: '/store-admin/login/',
  path: '/store-admin/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminAuthenticatedAnalyticsRouteRoute =
  StoreAdminAuthenticatedAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedStorageGatePassIndexRoute =
  StoreAdminAuthenticatedStorageGatePassIndexRouteImport.update({
    id: '/storage-gate-pass/',
    path: '/storage-gate-pass/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedSettingsIndexRoute =
  StoreAdminAuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleIndexRoute =
  StoreAdminAuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedNikasiGatePassIndexRoute =
  StoreAdminAuthenticatedNikasiGatePassIndexRouteImport.update({
    id: '/nikasi-gate-pass/',
    path: '/nikasi-gate-pass/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedIncomingGatePassIndexRoute =
  StoreAdminAuthenticatedIncomingGatePassIndexRouteImport.update({
    id: '/incoming-gate-pass/',
    path: '/incoming-gate-pass/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedGradingGatePassIndexRoute =
  StoreAdminAuthenticatedGradingGatePassIndexRouteImport.update({
    id: '/grading-gate-pass/',
    path: '/grading-gate-pass/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute =
  StoreAdminAuthenticatedFarmerSeedGatePassIndexRouteImport.update({
    id: '/farmer-seed-gate-pass/',
    path: '/farmer-seed-gate-pass/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedDaybookIndexRoute =
  StoreAdminAuthenticatedDaybookIndexRouteImport.update({
    id: '/daybook/',
    path: '/daybook/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedContractTestIndexRoute =
  StoreAdminAuthenticatedContractTestIndexRouteImport.update({
    id: '/contract-test/',
    path: '/contract-test/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsIndexRoute =
  StoreAdminAuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute =
  StoreAdminAuthenticatedStorageGatePassHistoryIndexRouteImport.update({
    id: '/storage-gate-pass/history/',
    path: '/storage-gate-pass/history/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedStorageGatePassEditIndexRoute =
  StoreAdminAuthenticatedStorageGatePassEditIndexRouteImport.update({
    id: '/storage-gate-pass/edit/',
    path: '/storage-gate-pass/edit/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedSettingsRbacIndexRoute =
  StoreAdminAuthenticatedSettingsRbacIndexRouteImport.update({
    id: '/settings/rbac/',
    path: '/settings/rbac/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedSettingsPreferencesIndexRoute =
  StoreAdminAuthenticatedSettingsPreferencesIndexRouteImport.update({
    id: '/settings/preferences/',
    path: '/settings/preferences/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedSettingsMasterIndexRoute =
  StoreAdminAuthenticatedSettingsMasterIndexRouteImport.update({
    id: '/settings/master/',
    path: '/settings/master/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute =
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport.update({
    id: '/people/$farmerStorageLinkId/',
    path: '/people/$farmerStorageLinkId/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute =
  StoreAdminAuthenticatedNikasiGatePassHistoryIndexRouteImport.update({
    id: '/nikasi-gate-pass/history/',
    path: '/nikasi-gate-pass/history/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedNikasiGatePassEditIndexRoute =
  StoreAdminAuthenticatedNikasiGatePassEditIndexRouteImport.update({
    id: '/nikasi-gate-pass/edit/',
    path: '/nikasi-gate-pass/edit/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute =
  StoreAdminAuthenticatedIncomingGatePassHistoryIndexRouteImport.update({
    id: '/incoming-gate-pass/history/',
    path: '/incoming-gate-pass/history/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedIncomingGatePassEditIndexRoute =
  StoreAdminAuthenticatedIncomingGatePassEditIndexRouteImport.update({
    id: '/incoming-gate-pass/edit/',
    path: '/incoming-gate-pass/edit/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute =
  StoreAdminAuthenticatedGradingGatePassHistoryIndexRouteImport.update({
    id: '/grading-gate-pass/history/',
    path: '/grading-gate-pass/history/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedGradingGatePassEditIndexRoute =
  StoreAdminAuthenticatedGradingGatePassEditIndexRouteImport.update({
    id: '/grading-gate-pass/edit/',
    path: '/grading-gate-pass/edit/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute =
  StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRouteImport.update({
    id: '/farmer-seed-gate-pass/history/',
    path: '/farmer-seed-gate-pass/history/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute =
  StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRouteImport.update({
    id: '/farmer-seed-gate-pass/edit/',
    path: '/farmer-seed-gate-pass/edit/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute =
  StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRouteImport.update({
    id: '/area-breakdown/',
    path: '/area-breakdown/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedSettingsMasterStationsIndexRoute =
  StoreAdminAuthenticatedSettingsMasterStationsIndexRouteImport.update({
    id: '/settings/master/stations/',
    path: '/settings/master/stations/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute =
  StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRouteImport.update({
    id: '/people/dispatch-ledger/$id/',
    path: '/people/dispatch-ledger/$id/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute =
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRouteImport.update(
    {
      id: '/people/$farmerStorageLinkId/finance-report/',
      path: '/people/$farmerStorageLinkId/finance-report/',
      getParentRoute: () => StoreAdminAuthenticatedRoute,
    } as any,
  )
const StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute =
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRouteImport.update(
    {
      id: '/people/$farmerStorageLinkId/farmer-report/',
      path: '/people/$farmerStorageLinkId/farmer-report/',
      getParentRoute: () => StoreAdminAuthenticatedRoute,
    } as any,
  )
const StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute =
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRouteImport.update(
    {
      id: '/people/$farmerStorageLinkId/accounting-report/',
      path: '/people/$farmerStorageLinkId/accounting-report/',
      getParentRoute: () => StoreAdminAuthenticatedRoute,
    } as any,
  )
const StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRouteImport.update({
    id: '/reports/ungraded/',
    path: '/reports/ungraded/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsStorageIndexRouteImport.update({
    id: '/reports/storage/',
    path: '/reports/storage/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsShedIndexRouteImport.update({
    id: '/reports/shed/',
    path: '/reports/shed/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRouteImport.update({
    id: '/reports/incoming/',
    path: '/reports/incoming/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsGradingIndexRouteImport.update({
    id: '/reports/grading/',
    path: '/reports/grading/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRouteImport.update({
    id: '/reports/farmer-seed/',
    path: '/reports/farmer-seed/',
    getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRouteImport.update(
    {
      id: '/reports/dispatch-pre-storage/',
      path: '/reports/dispatch-pre-storage/',
      getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
    } as any,
  )
const StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute =
  StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRouteImport.update(
    {
      id: '/reports/contract-farming/',
      path: '/reports/contract-farming/',
      getParentRoute: () => StoreAdminAuthenticatedAnalyticsRouteRoute,
    } as any,
  )
const StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute =
  StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRouteImport.update(
    {
      id: '/people/dispatch-ledger/$id/dispatch-ledger-report/',
      path: '/people/dispatch-ledger/$id/dispatch-ledger-report/',
      getParentRoute: () => StoreAdminAuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store-admin': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand/': typeof ZustandIndexRoute
  '/store-admin/analytics': typeof StoreAdminAuthenticatedAnalyticsRouteRouteWithChildren
  '/store-admin/login/': typeof StoreAdminLoginIndexRoute
  '/store-admin/analytics/': typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  '/store-admin/contract-test/': typeof StoreAdminAuthenticatedContractTestIndexRoute
  '/store-admin/daybook/': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/farmer-seed-gate-pass/': typeof StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute
  '/store-admin/grading-gate-pass/': typeof StoreAdminAuthenticatedGradingGatePassIndexRoute
  '/store-admin/incoming-gate-pass/': typeof StoreAdminAuthenticatedIncomingGatePassIndexRoute
  '/store-admin/nikasi-gate-pass/': typeof StoreAdminAuthenticatedNikasiGatePassIndexRoute
  '/store-admin/people/': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/settings/': typeof StoreAdminAuthenticatedSettingsIndexRoute
  '/store-admin/storage-gate-pass/': typeof StoreAdminAuthenticatedStorageGatePassIndexRoute
  '/store-admin/analytics/area-breakdown/': typeof StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute
  '/store-admin/farmer-seed-gate-pass/edit/': typeof StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute
  '/store-admin/farmer-seed-gate-pass/history/': typeof StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute
  '/store-admin/grading-gate-pass/edit/': typeof StoreAdminAuthenticatedGradingGatePassEditIndexRoute
  '/store-admin/grading-gate-pass/history/': typeof StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute
  '/store-admin/incoming-gate-pass/edit/': typeof StoreAdminAuthenticatedIncomingGatePassEditIndexRoute
  '/store-admin/incoming-gate-pass/history/': typeof StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute
  '/store-admin/nikasi-gate-pass/edit/': typeof StoreAdminAuthenticatedNikasiGatePassEditIndexRoute
  '/store-admin/nikasi-gate-pass/history/': typeof StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute
  '/store-admin/people/$farmerStorageLinkId/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
  '/store-admin/settings/master/': typeof StoreAdminAuthenticatedSettingsMasterIndexRoute
  '/store-admin/settings/preferences/': typeof StoreAdminAuthenticatedSettingsPreferencesIndexRoute
  '/store-admin/settings/rbac/': typeof StoreAdminAuthenticatedSettingsRbacIndexRoute
  '/store-admin/storage-gate-pass/edit/': typeof StoreAdminAuthenticatedStorageGatePassEditIndexRoute
  '/store-admin/storage-gate-pass/history/': typeof StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute
  '/store-admin/analytics/reports/contract-farming/': typeof StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute
  '/store-admin/analytics/reports/dispatch-pre-storage/': typeof StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute
  '/store-admin/analytics/reports/farmer-seed/': typeof StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute
  '/store-admin/analytics/reports/grading/': typeof StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute
  '/store-admin/analytics/reports/incoming/': typeof StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute
  '/store-admin/analytics/reports/shed/': typeof StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute
  '/store-admin/analytics/reports/storage/': typeof StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute
  '/store-admin/analytics/reports/ungraded/': typeof StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute
  '/store-admin/people/$farmerStorageLinkId/accounting-report/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute
  '/store-admin/people/$farmerStorageLinkId/farmer-report/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute
  '/store-admin/people/$farmerStorageLinkId/finance-report/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute
  '/store-admin/people/dispatch-ledger/$id/': typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute
  '/store-admin/settings/master/stations/': typeof StoreAdminAuthenticatedSettingsMasterStationsIndexRoute
  '/store-admin/people/dispatch-ledger/$id/dispatch-ledger-report/': typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store-admin': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand': typeof ZustandIndexRoute
  '/store-admin/login': typeof StoreAdminLoginIndexRoute
  '/store-admin/analytics': typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  '/store-admin/contract-test': typeof StoreAdminAuthenticatedContractTestIndexRoute
  '/store-admin/daybook': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/farmer-seed-gate-pass': typeof StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute
  '/store-admin/grading-gate-pass': typeof StoreAdminAuthenticatedGradingGatePassIndexRoute
  '/store-admin/incoming-gate-pass': typeof StoreAdminAuthenticatedIncomingGatePassIndexRoute
  '/store-admin/nikasi-gate-pass': typeof StoreAdminAuthenticatedNikasiGatePassIndexRoute
  '/store-admin/people': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/settings': typeof StoreAdminAuthenticatedSettingsIndexRoute
  '/store-admin/storage-gate-pass': typeof StoreAdminAuthenticatedStorageGatePassIndexRoute
  '/store-admin/analytics/area-breakdown': typeof StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute
  '/store-admin/farmer-seed-gate-pass/edit': typeof StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute
  '/store-admin/farmer-seed-gate-pass/history': typeof StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute
  '/store-admin/grading-gate-pass/edit': typeof StoreAdminAuthenticatedGradingGatePassEditIndexRoute
  '/store-admin/grading-gate-pass/history': typeof StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute
  '/store-admin/incoming-gate-pass/edit': typeof StoreAdminAuthenticatedIncomingGatePassEditIndexRoute
  '/store-admin/incoming-gate-pass/history': typeof StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute
  '/store-admin/nikasi-gate-pass/edit': typeof StoreAdminAuthenticatedNikasiGatePassEditIndexRoute
  '/store-admin/nikasi-gate-pass/history': typeof StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute
  '/store-admin/people/$farmerStorageLinkId': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
  '/store-admin/settings/master': typeof StoreAdminAuthenticatedSettingsMasterIndexRoute
  '/store-admin/settings/preferences': typeof StoreAdminAuthenticatedSettingsPreferencesIndexRoute
  '/store-admin/settings/rbac': typeof StoreAdminAuthenticatedSettingsRbacIndexRoute
  '/store-admin/storage-gate-pass/edit': typeof StoreAdminAuthenticatedStorageGatePassEditIndexRoute
  '/store-admin/storage-gate-pass/history': typeof StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute
  '/store-admin/analytics/reports/contract-farming': typeof StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute
  '/store-admin/analytics/reports/dispatch-pre-storage': typeof StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute
  '/store-admin/analytics/reports/farmer-seed': typeof StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute
  '/store-admin/analytics/reports/grading': typeof StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute
  '/store-admin/analytics/reports/incoming': typeof StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute
  '/store-admin/analytics/reports/shed': typeof StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute
  '/store-admin/analytics/reports/storage': typeof StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute
  '/store-admin/analytics/reports/ungraded': typeof StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute
  '/store-admin/people/$farmerStorageLinkId/accounting-report': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute
  '/store-admin/people/$farmerStorageLinkId/farmer-report': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute
  '/store-admin/people/$farmerStorageLinkId/finance-report': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute
  '/store-admin/people/dispatch-ledger/$id': typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute
  '/store-admin/settings/master/stations': typeof StoreAdminAuthenticatedSettingsMasterStationsIndexRoute
  '/store-admin/people/dispatch-ledger/$id/dispatch-ledger-report': typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/store-admin/_authenticated': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand/': typeof ZustandIndexRoute
  '/store-admin/_authenticated/analytics': typeof StoreAdminAuthenticatedAnalyticsRouteRouteWithChildren
  '/store-admin/login/': typeof StoreAdminLoginIndexRoute
  '/store-admin/_authenticated/analytics/': typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  '/store-admin/_authenticated/contract-test/': typeof StoreAdminAuthenticatedContractTestIndexRoute
  '/store-admin/_authenticated/daybook/': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/_authenticated/farmer-seed-gate-pass/': typeof StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute
  '/store-admin/_authenticated/grading-gate-pass/': typeof StoreAdminAuthenticatedGradingGatePassIndexRoute
  '/store-admin/_authenticated/incoming-gate-pass/': typeof StoreAdminAuthenticatedIncomingGatePassIndexRoute
  '/store-admin/_authenticated/nikasi-gate-pass/': typeof StoreAdminAuthenticatedNikasiGatePassIndexRoute
  '/store-admin/_authenticated/people/': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/_authenticated/settings/': typeof StoreAdminAuthenticatedSettingsIndexRoute
  '/store-admin/_authenticated/storage-gate-pass/': typeof StoreAdminAuthenticatedStorageGatePassIndexRoute
  '/store-admin/_authenticated/analytics/area-breakdown/': typeof StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute
  '/store-admin/_authenticated/farmer-seed-gate-pass/edit/': typeof StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute
  '/store-admin/_authenticated/farmer-seed-gate-pass/history/': typeof StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute
  '/store-admin/_authenticated/grading-gate-pass/edit/': typeof StoreAdminAuthenticatedGradingGatePassEditIndexRoute
  '/store-admin/_authenticated/grading-gate-pass/history/': typeof StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute
  '/store-admin/_authenticated/incoming-gate-pass/edit/': typeof StoreAdminAuthenticatedIncomingGatePassEditIndexRoute
  '/store-admin/_authenticated/incoming-gate-pass/history/': typeof StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute
  '/store-admin/_authenticated/nikasi-gate-pass/edit/': typeof StoreAdminAuthenticatedNikasiGatePassEditIndexRoute
  '/store-admin/_authenticated/nikasi-gate-pass/history/': typeof StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute
  '/store-admin/_authenticated/people/$farmerStorageLinkId/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
  '/store-admin/_authenticated/settings/master/': typeof StoreAdminAuthenticatedSettingsMasterIndexRoute
  '/store-admin/_authenticated/settings/preferences/': typeof StoreAdminAuthenticatedSettingsPreferencesIndexRoute
  '/store-admin/_authenticated/settings/rbac/': typeof StoreAdminAuthenticatedSettingsRbacIndexRoute
  '/store-admin/_authenticated/storage-gate-pass/edit/': typeof StoreAdminAuthenticatedStorageGatePassEditIndexRoute
  '/store-admin/_authenticated/storage-gate-pass/history/': typeof StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute
  '/store-admin/_authenticated/analytics/reports/contract-farming/': typeof StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute
  '/store-admin/_authenticated/analytics/reports/dispatch-pre-storage/': typeof StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute
  '/store-admin/_authenticated/analytics/reports/farmer-seed/': typeof StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute
  '/store-admin/_authenticated/analytics/reports/grading/': typeof StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute
  '/store-admin/_authenticated/analytics/reports/incoming/': typeof StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute
  '/store-admin/_authenticated/analytics/reports/shed/': typeof StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute
  '/store-admin/_authenticated/analytics/reports/storage/': typeof StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute
  '/store-admin/_authenticated/analytics/reports/ungraded/': typeof StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute
  '/store-admin/_authenticated/people/$farmerStorageLinkId/accounting-report/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute
  '/store-admin/_authenticated/people/$farmerStorageLinkId/farmer-report/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute
  '/store-admin/_authenticated/people/$farmerStorageLinkId/finance-report/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute
  '/store-admin/_authenticated/people/dispatch-ledger/$id/': typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute
  '/store-admin/_authenticated/settings/master/stations/': typeof StoreAdminAuthenticatedSettingsMasterStationsIndexRoute
  '/store-admin/_authenticated/people/dispatch-ledger/$id/dispatch-ledger-report/': typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/store-admin'
    | '/zustand/'
    | '/store-admin/analytics'
    | '/store-admin/login/'
    | '/store-admin/analytics/'
    | '/store-admin/contract-test/'
    | '/store-admin/daybook/'
    | '/store-admin/farmer-seed-gate-pass/'
    | '/store-admin/grading-gate-pass/'
    | '/store-admin/incoming-gate-pass/'
    | '/store-admin/nikasi-gate-pass/'
    | '/store-admin/people/'
    | '/store-admin/settings/'
    | '/store-admin/storage-gate-pass/'
    | '/store-admin/analytics/area-breakdown/'
    | '/store-admin/farmer-seed-gate-pass/edit/'
    | '/store-admin/farmer-seed-gate-pass/history/'
    | '/store-admin/grading-gate-pass/edit/'
    | '/store-admin/grading-gate-pass/history/'
    | '/store-admin/incoming-gate-pass/edit/'
    | '/store-admin/incoming-gate-pass/history/'
    | '/store-admin/nikasi-gate-pass/edit/'
    | '/store-admin/nikasi-gate-pass/history/'
    | '/store-admin/people/$farmerStorageLinkId/'
    | '/store-admin/settings/master/'
    | '/store-admin/settings/preferences/'
    | '/store-admin/settings/rbac/'
    | '/store-admin/storage-gate-pass/edit/'
    | '/store-admin/storage-gate-pass/history/'
    | '/store-admin/analytics/reports/contract-farming/'
    | '/store-admin/analytics/reports/dispatch-pre-storage/'
    | '/store-admin/analytics/reports/farmer-seed/'
    | '/store-admin/analytics/reports/grading/'
    | '/store-admin/analytics/reports/incoming/'
    | '/store-admin/analytics/reports/shed/'
    | '/store-admin/analytics/reports/storage/'
    | '/store-admin/analytics/reports/ungraded/'
    | '/store-admin/people/$farmerStorageLinkId/accounting-report/'
    | '/store-admin/people/$farmerStorageLinkId/farmer-report/'
    | '/store-admin/people/$farmerStorageLinkId/finance-report/'
    | '/store-admin/people/dispatch-ledger/$id/'
    | '/store-admin/settings/master/stations/'
    | '/store-admin/people/dispatch-ledger/$id/dispatch-ledger-report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/store-admin'
    | '/zustand'
    | '/store-admin/login'
    | '/store-admin/analytics'
    | '/store-admin/contract-test'
    | '/store-admin/daybook'
    | '/store-admin/farmer-seed-gate-pass'
    | '/store-admin/grading-gate-pass'
    | '/store-admin/incoming-gate-pass'
    | '/store-admin/nikasi-gate-pass'
    | '/store-admin/people'
    | '/store-admin/settings'
    | '/store-admin/storage-gate-pass'
    | '/store-admin/analytics/area-breakdown'
    | '/store-admin/farmer-seed-gate-pass/edit'
    | '/store-admin/farmer-seed-gate-pass/history'
    | '/store-admin/grading-gate-pass/edit'
    | '/store-admin/grading-gate-pass/history'
    | '/store-admin/incoming-gate-pass/edit'
    | '/store-admin/incoming-gate-pass/history'
    | '/store-admin/nikasi-gate-pass/edit'
    | '/store-admin/nikasi-gate-pass/history'
    | '/store-admin/people/$farmerStorageLinkId'
    | '/store-admin/settings/master'
    | '/store-admin/settings/preferences'
    | '/store-admin/settings/rbac'
    | '/store-admin/storage-gate-pass/edit'
    | '/store-admin/storage-gate-pass/history'
    | '/store-admin/analytics/reports/contract-farming'
    | '/store-admin/analytics/reports/dispatch-pre-storage'
    | '/store-admin/analytics/reports/farmer-seed'
    | '/store-admin/analytics/reports/grading'
    | '/store-admin/analytics/reports/incoming'
    | '/store-admin/analytics/reports/shed'
    | '/store-admin/analytics/reports/storage'
    | '/store-admin/analytics/reports/ungraded'
    | '/store-admin/people/$farmerStorageLinkId/accounting-report'
    | '/store-admin/people/$farmerStorageLinkId/farmer-report'
    | '/store-admin/people/$farmerStorageLinkId/finance-report'
    | '/store-admin/people/dispatch-ledger/$id'
    | '/store-admin/settings/master/stations'
    | '/store-admin/people/dispatch-ledger/$id/dispatch-ledger-report'
  id:
    | '__root__'
    | '/'
    | '/store-admin/_authenticated'
    | '/zustand/'
    | '/store-admin/_authenticated/analytics'
    | '/store-admin/login/'
    | '/store-admin/_authenticated/analytics/'
    | '/store-admin/_authenticated/contract-test/'
    | '/store-admin/_authenticated/daybook/'
    | '/store-admin/_authenticated/farmer-seed-gate-pass/'
    | '/store-admin/_authenticated/grading-gate-pass/'
    | '/store-admin/_authenticated/incoming-gate-pass/'
    | '/store-admin/_authenticated/nikasi-gate-pass/'
    | '/store-admin/_authenticated/people/'
    | '/store-admin/_authenticated/settings/'
    | '/store-admin/_authenticated/storage-gate-pass/'
    | '/store-admin/_authenticated/analytics/area-breakdown/'
    | '/store-admin/_authenticated/farmer-seed-gate-pass/edit/'
    | '/store-admin/_authenticated/farmer-seed-gate-pass/history/'
    | '/store-admin/_authenticated/grading-gate-pass/edit/'
    | '/store-admin/_authenticated/grading-gate-pass/history/'
    | '/store-admin/_authenticated/incoming-gate-pass/edit/'
    | '/store-admin/_authenticated/incoming-gate-pass/history/'
    | '/store-admin/_authenticated/nikasi-gate-pass/edit/'
    | '/store-admin/_authenticated/nikasi-gate-pass/history/'
    | '/store-admin/_authenticated/people/$farmerStorageLinkId/'
    | '/store-admin/_authenticated/settings/master/'
    | '/store-admin/_authenticated/settings/preferences/'
    | '/store-admin/_authenticated/settings/rbac/'
    | '/store-admin/_authenticated/storage-gate-pass/edit/'
    | '/store-admin/_authenticated/storage-gate-pass/history/'
    | '/store-admin/_authenticated/analytics/reports/contract-farming/'
    | '/store-admin/_authenticated/analytics/reports/dispatch-pre-storage/'
    | '/store-admin/_authenticated/analytics/reports/farmer-seed/'
    | '/store-admin/_authenticated/analytics/reports/grading/'
    | '/store-admin/_authenticated/analytics/reports/incoming/'
    | '/store-admin/_authenticated/analytics/reports/shed/'
    | '/store-admin/_authenticated/analytics/reports/storage/'
    | '/store-admin/_authenticated/analytics/reports/ungraded/'
    | '/store-admin/_authenticated/people/$farmerStorageLinkId/accounting-report/'
    | '/store-admin/_authenticated/people/$farmerStorageLinkId/farmer-report/'
    | '/store-admin/_authenticated/people/$farmerStorageLinkId/finance-report/'
    | '/store-admin/_authenticated/people/dispatch-ledger/$id/'
    | '/store-admin/_authenticated/settings/master/stations/'
    | '/store-admin/_authenticated/people/dispatch-ledger/$id/dispatch-ledger-report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreAdminAuthenticatedRoute: typeof StoreAdminAuthenticatedRouteWithChildren
  ZustandIndexRoute: typeof ZustandIndexRoute
  StoreAdminLoginIndexRoute: typeof StoreAdminLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zustand/': {
      id: '/zustand/'
      path: '/zustand'
      fullPath: '/zustand/'
      preLoaderRoute: typeof ZustandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/_authenticated': {
      id: '/store-admin/_authenticated'
      path: '/store-admin'
      fullPath: '/store-admin'
      preLoaderRoute: typeof StoreAdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/login/': {
      id: '/store-admin/login/'
      path: '/store-admin/login'
      fullPath: '/store-admin/login/'
      preLoaderRoute: typeof StoreAdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/_authenticated/analytics': {
      id: '/store-admin/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/store-admin/analytics'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/storage-gate-pass/': {
      id: '/store-admin/_authenticated/storage-gate-pass/'
      path: '/storage-gate-pass'
      fullPath: '/store-admin/storage-gate-pass/'
      preLoaderRoute: typeof StoreAdminAuthenticatedStorageGatePassIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/settings/': {
      id: '/store-admin/_authenticated/settings/'
      path: '/settings'
      fullPath: '/store-admin/settings/'
      preLoaderRoute: typeof StoreAdminAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/': {
      id: '/store-admin/_authenticated/people/'
      path: '/people'
      fullPath: '/store-admin/people/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/nikasi-gate-pass/': {
      id: '/store-admin/_authenticated/nikasi-gate-pass/'
      path: '/nikasi-gate-pass'
      fullPath: '/store-admin/nikasi-gate-pass/'
      preLoaderRoute: typeof StoreAdminAuthenticatedNikasiGatePassIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/incoming-gate-pass/': {
      id: '/store-admin/_authenticated/incoming-gate-pass/'
      path: '/incoming-gate-pass'
      fullPath: '/store-admin/incoming-gate-pass/'
      preLoaderRoute: typeof StoreAdminAuthenticatedIncomingGatePassIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/grading-gate-pass/': {
      id: '/store-admin/_authenticated/grading-gate-pass/'
      path: '/grading-gate-pass'
      fullPath: '/store-admin/grading-gate-pass/'
      preLoaderRoute: typeof StoreAdminAuthenticatedGradingGatePassIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/farmer-seed-gate-pass/': {
      id: '/store-admin/_authenticated/farmer-seed-gate-pass/'
      path: '/farmer-seed-gate-pass'
      fullPath: '/store-admin/farmer-seed-gate-pass/'
      preLoaderRoute: typeof StoreAdminAuthenticatedFarmerSeedGatePassIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/daybook/': {
      id: '/store-admin/_authenticated/daybook/'
      path: '/daybook'
      fullPath: '/store-admin/daybook/'
      preLoaderRoute: typeof StoreAdminAuthenticatedDaybookIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/contract-test/': {
      id: '/store-admin/_authenticated/contract-test/'
      path: '/contract-test'
      fullPath: '/store-admin/contract-test/'
      preLoaderRoute: typeof StoreAdminAuthenticatedContractTestIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/analytics/': {
      id: '/store-admin/_authenticated/analytics/'
      path: '/'
      fullPath: '/store-admin/analytics/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/storage-gate-pass/history/': {
      id: '/store-admin/_authenticated/storage-gate-pass/history/'
      path: '/storage-gate-pass/history'
      fullPath: '/store-admin/storage-gate-pass/history/'
      preLoaderRoute: typeof StoreAdminAuthenticatedStorageGatePassHistoryIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/storage-gate-pass/edit/': {
      id: '/store-admin/_authenticated/storage-gate-pass/edit/'
      path: '/storage-gate-pass/edit'
      fullPath: '/store-admin/storage-gate-pass/edit/'
      preLoaderRoute: typeof StoreAdminAuthenticatedStorageGatePassEditIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/settings/rbac/': {
      id: '/store-admin/_authenticated/settings/rbac/'
      path: '/settings/rbac'
      fullPath: '/store-admin/settings/rbac/'
      preLoaderRoute: typeof StoreAdminAuthenticatedSettingsRbacIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/settings/preferences/': {
      id: '/store-admin/_authenticated/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/store-admin/settings/preferences/'
      preLoaderRoute: typeof StoreAdminAuthenticatedSettingsPreferencesIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/settings/master/': {
      id: '/store-admin/_authenticated/settings/master/'
      path: '/settings/master'
      fullPath: '/store-admin/settings/master/'
      preLoaderRoute: typeof StoreAdminAuthenticatedSettingsMasterIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/$farmerStorageLinkId/': {
      id: '/store-admin/_authenticated/people/$farmerStorageLinkId/'
      path: '/people/$farmerStorageLinkId'
      fullPath: '/store-admin/people/$farmerStorageLinkId/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/nikasi-gate-pass/history/': {
      id: '/store-admin/_authenticated/nikasi-gate-pass/history/'
      path: '/nikasi-gate-pass/history'
      fullPath: '/store-admin/nikasi-gate-pass/history/'
      preLoaderRoute: typeof StoreAdminAuthenticatedNikasiGatePassHistoryIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/nikasi-gate-pass/edit/': {
      id: '/store-admin/_authenticated/nikasi-gate-pass/edit/'
      path: '/nikasi-gate-pass/edit'
      fullPath: '/store-admin/nikasi-gate-pass/edit/'
      preLoaderRoute: typeof StoreAdminAuthenticatedNikasiGatePassEditIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/incoming-gate-pass/history/': {
      id: '/store-admin/_authenticated/incoming-gate-pass/history/'
      path: '/incoming-gate-pass/history'
      fullPath: '/store-admin/incoming-gate-pass/history/'
      preLoaderRoute: typeof StoreAdminAuthenticatedIncomingGatePassHistoryIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/incoming-gate-pass/edit/': {
      id: '/store-admin/_authenticated/incoming-gate-pass/edit/'
      path: '/incoming-gate-pass/edit'
      fullPath: '/store-admin/incoming-gate-pass/edit/'
      preLoaderRoute: typeof StoreAdminAuthenticatedIncomingGatePassEditIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/grading-gate-pass/history/': {
      id: '/store-admin/_authenticated/grading-gate-pass/history/'
      path: '/grading-gate-pass/history'
      fullPath: '/store-admin/grading-gate-pass/history/'
      preLoaderRoute: typeof StoreAdminAuthenticatedGradingGatePassHistoryIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/grading-gate-pass/edit/': {
      id: '/store-admin/_authenticated/grading-gate-pass/edit/'
      path: '/grading-gate-pass/edit'
      fullPath: '/store-admin/grading-gate-pass/edit/'
      preLoaderRoute: typeof StoreAdminAuthenticatedGradingGatePassEditIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/farmer-seed-gate-pass/history/': {
      id: '/store-admin/_authenticated/farmer-seed-gate-pass/history/'
      path: '/farmer-seed-gate-pass/history'
      fullPath: '/store-admin/farmer-seed-gate-pass/history/'
      preLoaderRoute: typeof StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/farmer-seed-gate-pass/edit/': {
      id: '/store-admin/_authenticated/farmer-seed-gate-pass/edit/'
      path: '/farmer-seed-gate-pass/edit'
      fullPath: '/store-admin/farmer-seed-gate-pass/edit/'
      preLoaderRoute: typeof StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/analytics/area-breakdown/': {
      id: '/store-admin/_authenticated/analytics/area-breakdown/'
      path: '/area-breakdown'
      fullPath: '/store-admin/analytics/area-breakdown/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/settings/master/stations/': {
      id: '/store-admin/_authenticated/settings/master/stations/'
      path: '/settings/master/stations'
      fullPath: '/store-admin/settings/master/stations/'
      preLoaderRoute: typeof StoreAdminAuthenticatedSettingsMasterStationsIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/dispatch-ledger/$id/': {
      id: '/store-admin/_authenticated/people/dispatch-ledger/$id/'
      path: '/people/dispatch-ledger/$id'
      fullPath: '/store-admin/people/dispatch-ledger/$id/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/$farmerStorageLinkId/finance-report/': {
      id: '/store-admin/_authenticated/people/$farmerStorageLinkId/finance-report/'
      path: '/people/$farmerStorageLinkId/finance-report'
      fullPath: '/store-admin/people/$farmerStorageLinkId/finance-report/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/$farmerStorageLinkId/farmer-report/': {
      id: '/store-admin/_authenticated/people/$farmerStorageLinkId/farmer-report/'
      path: '/people/$farmerStorageLinkId/farmer-report'
      fullPath: '/store-admin/people/$farmerStorageLinkId/farmer-report/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/$farmerStorageLinkId/accounting-report/': {
      id: '/store-admin/_authenticated/people/$farmerStorageLinkId/accounting-report/'
      path: '/people/$farmerStorageLinkId/accounting-report'
      fullPath: '/store-admin/people/$farmerStorageLinkId/accounting-report/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/analytics/reports/ungraded/': {
      id: '/store-admin/_authenticated/analytics/reports/ungraded/'
      path: '/reports/ungraded'
      fullPath: '/store-admin/analytics/reports/ungraded/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/storage/': {
      id: '/store-admin/_authenticated/analytics/reports/storage/'
      path: '/reports/storage'
      fullPath: '/store-admin/analytics/reports/storage/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsStorageIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/shed/': {
      id: '/store-admin/_authenticated/analytics/reports/shed/'
      path: '/reports/shed'
      fullPath: '/store-admin/analytics/reports/shed/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsShedIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/incoming/': {
      id: '/store-admin/_authenticated/analytics/reports/incoming/'
      path: '/reports/incoming'
      fullPath: '/store-admin/analytics/reports/incoming/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/grading/': {
      id: '/store-admin/_authenticated/analytics/reports/grading/'
      path: '/reports/grading'
      fullPath: '/store-admin/analytics/reports/grading/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsGradingIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/farmer-seed/': {
      id: '/store-admin/_authenticated/analytics/reports/farmer-seed/'
      path: '/reports/farmer-seed'
      fullPath: '/store-admin/analytics/reports/farmer-seed/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/dispatch-pre-storage/': {
      id: '/store-admin/_authenticated/analytics/reports/dispatch-pre-storage/'
      path: '/reports/dispatch-pre-storage'
      fullPath: '/store-admin/analytics/reports/dispatch-pre-storage/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/analytics/reports/contract-farming/': {
      id: '/store-admin/_authenticated/analytics/reports/contract-farming/'
      path: '/reports/contract-farming'
      fullPath: '/store-admin/analytics/reports/contract-farming/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRoute
    }
    '/store-admin/_authenticated/people/dispatch-ledger/$id/dispatch-ledger-report/': {
      id: '/store-admin/_authenticated/people/dispatch-ledger/$id/dispatch-ledger-report/'
      path: '/people/dispatch-ledger/$id/dispatch-ledger-report'
      fullPath: '/store-admin/people/dispatch-ledger/$id/dispatch-ledger-report/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
  }
}

interface StoreAdminAuthenticatedAnalyticsRouteRouteChildren {
  StoreAdminAuthenticatedAnalyticsIndexRoute: typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute: typeof StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute
  StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute: typeof StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute
}

const StoreAdminAuthenticatedAnalyticsRouteRouteChildren: StoreAdminAuthenticatedAnalyticsRouteRouteChildren =
  {
    StoreAdminAuthenticatedAnalyticsIndexRoute:
      StoreAdminAuthenticatedAnalyticsIndexRoute,
    StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute:
      StoreAdminAuthenticatedAnalyticsAreaBreakdownIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsContractFarmingIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsDispatchPreStorageIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsFarmerSeedIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsGradingIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsIncomingIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsShedIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsStorageIndexRoute,
    StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute:
      StoreAdminAuthenticatedAnalyticsReportsUngradedIndexRoute,
  }

const StoreAdminAuthenticatedAnalyticsRouteRouteWithChildren =
  StoreAdminAuthenticatedAnalyticsRouteRoute._addFileChildren(
    StoreAdminAuthenticatedAnalyticsRouteRouteChildren,
  )

interface StoreAdminAuthenticatedRouteChildren {
  StoreAdminAuthenticatedAnalyticsRouteRoute: typeof StoreAdminAuthenticatedAnalyticsRouteRouteWithChildren
  StoreAdminAuthenticatedContractTestIndexRoute: typeof StoreAdminAuthenticatedContractTestIndexRoute
  StoreAdminAuthenticatedDaybookIndexRoute: typeof StoreAdminAuthenticatedDaybookIndexRoute
  StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute: typeof StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute
  StoreAdminAuthenticatedGradingGatePassIndexRoute: typeof StoreAdminAuthenticatedGradingGatePassIndexRoute
  StoreAdminAuthenticatedIncomingGatePassIndexRoute: typeof StoreAdminAuthenticatedIncomingGatePassIndexRoute
  StoreAdminAuthenticatedNikasiGatePassIndexRoute: typeof StoreAdminAuthenticatedNikasiGatePassIndexRoute
  StoreAdminAuthenticatedPeopleIndexRoute: typeof StoreAdminAuthenticatedPeopleIndexRoute
  StoreAdminAuthenticatedSettingsIndexRoute: typeof StoreAdminAuthenticatedSettingsIndexRoute
  StoreAdminAuthenticatedStorageGatePassIndexRoute: typeof StoreAdminAuthenticatedStorageGatePassIndexRoute
  StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute: typeof StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute
  StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute: typeof StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute
  StoreAdminAuthenticatedGradingGatePassEditIndexRoute: typeof StoreAdminAuthenticatedGradingGatePassEditIndexRoute
  StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute: typeof StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute
  StoreAdminAuthenticatedIncomingGatePassEditIndexRoute: typeof StoreAdminAuthenticatedIncomingGatePassEditIndexRoute
  StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute: typeof StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute
  StoreAdminAuthenticatedNikasiGatePassEditIndexRoute: typeof StoreAdminAuthenticatedNikasiGatePassEditIndexRoute
  StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute: typeof StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
  StoreAdminAuthenticatedSettingsMasterIndexRoute: typeof StoreAdminAuthenticatedSettingsMasterIndexRoute
  StoreAdminAuthenticatedSettingsPreferencesIndexRoute: typeof StoreAdminAuthenticatedSettingsPreferencesIndexRoute
  StoreAdminAuthenticatedSettingsRbacIndexRoute: typeof StoreAdminAuthenticatedSettingsRbacIndexRoute
  StoreAdminAuthenticatedStorageGatePassEditIndexRoute: typeof StoreAdminAuthenticatedStorageGatePassEditIndexRoute
  StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute: typeof StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute
  StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute: typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute
  StoreAdminAuthenticatedSettingsMasterStationsIndexRoute: typeof StoreAdminAuthenticatedSettingsMasterStationsIndexRoute
  StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute: typeof StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute
}

const StoreAdminAuthenticatedRouteChildren: StoreAdminAuthenticatedRouteChildren =
  {
    StoreAdminAuthenticatedAnalyticsRouteRoute:
      StoreAdminAuthenticatedAnalyticsRouteRouteWithChildren,
    StoreAdminAuthenticatedContractTestIndexRoute:
      StoreAdminAuthenticatedContractTestIndexRoute,
    StoreAdminAuthenticatedDaybookIndexRoute:
      StoreAdminAuthenticatedDaybookIndexRoute,
    StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute:
      StoreAdminAuthenticatedFarmerSeedGatePassIndexRoute,
    StoreAdminAuthenticatedGradingGatePassIndexRoute:
      StoreAdminAuthenticatedGradingGatePassIndexRoute,
    StoreAdminAuthenticatedIncomingGatePassIndexRoute:
      StoreAdminAuthenticatedIncomingGatePassIndexRoute,
    StoreAdminAuthenticatedNikasiGatePassIndexRoute:
      StoreAdminAuthenticatedNikasiGatePassIndexRoute,
    StoreAdminAuthenticatedPeopleIndexRoute:
      StoreAdminAuthenticatedPeopleIndexRoute,
    StoreAdminAuthenticatedSettingsIndexRoute:
      StoreAdminAuthenticatedSettingsIndexRoute,
    StoreAdminAuthenticatedStorageGatePassIndexRoute:
      StoreAdminAuthenticatedStorageGatePassIndexRoute,
    StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute:
      StoreAdminAuthenticatedFarmerSeedGatePassEditIndexRoute,
    StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute:
      StoreAdminAuthenticatedFarmerSeedGatePassHistoryIndexRoute,
    StoreAdminAuthenticatedGradingGatePassEditIndexRoute:
      StoreAdminAuthenticatedGradingGatePassEditIndexRoute,
    StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute:
      StoreAdminAuthenticatedGradingGatePassHistoryIndexRoute,
    StoreAdminAuthenticatedIncomingGatePassEditIndexRoute:
      StoreAdminAuthenticatedIncomingGatePassEditIndexRoute,
    StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute:
      StoreAdminAuthenticatedIncomingGatePassHistoryIndexRoute,
    StoreAdminAuthenticatedNikasiGatePassEditIndexRoute:
      StoreAdminAuthenticatedNikasiGatePassEditIndexRoute,
    StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute:
      StoreAdminAuthenticatedNikasiGatePassHistoryIndexRoute,
    StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute:
      StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute,
    StoreAdminAuthenticatedSettingsMasterIndexRoute:
      StoreAdminAuthenticatedSettingsMasterIndexRoute,
    StoreAdminAuthenticatedSettingsPreferencesIndexRoute:
      StoreAdminAuthenticatedSettingsPreferencesIndexRoute,
    StoreAdminAuthenticatedSettingsRbacIndexRoute:
      StoreAdminAuthenticatedSettingsRbacIndexRoute,
    StoreAdminAuthenticatedStorageGatePassEditIndexRoute:
      StoreAdminAuthenticatedStorageGatePassEditIndexRoute,
    StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute:
      StoreAdminAuthenticatedStorageGatePassHistoryIndexRoute,
    StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute:
      StoreAdminAuthenticatedPeopleFarmerStorageLinkIdAccountingReportIndexRoute,
    StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute:
      StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFarmerReportIndexRoute,
    StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute:
      StoreAdminAuthenticatedPeopleFarmerStorageLinkIdFinanceReportIndexRoute,
    StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute:
      StoreAdminAuthenticatedPeopleDispatchLedgerIdIndexRoute,
    StoreAdminAuthenticatedSettingsMasterStationsIndexRoute:
      StoreAdminAuthenticatedSettingsMasterStationsIndexRoute,
    StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute:
      StoreAdminAuthenticatedPeopleDispatchLedgerIdDispatchLedgerReportIndexRoute,
  }

const StoreAdminAuthenticatedRouteWithChildren =
  StoreAdminAuthenticatedRoute._addFileChildren(
    StoreAdminAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreAdminAuthenticatedRoute: StoreAdminAuthenticatedRouteWithChildren,
  ZustandIndexRoute: ZustandIndexRoute,
  StoreAdminLoginIndexRoute: StoreAdminLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
