/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZustandIndexRouteImport } from './routes/zustand/index'
import { Route as StoreAdminAuthenticatedRouteImport } from './routes/store-admin/_authenticated'
import { Route as StoreAdminLoginIndexRouteImport } from './routes/store-admin/login/index'
import { Route as StoreAdminAuthenticatedStorageIndexRouteImport } from './routes/store-admin/_authenticated/storage/index'
import { Route as StoreAdminAuthenticatedPeopleIndexRouteImport } from './routes/store-admin/_authenticated/people/index'
import { Route as StoreAdminAuthenticatedOutgoingIndexRouteImport } from './routes/store-admin/_authenticated/outgoing/index'
import { Route as StoreAdminAuthenticatedNikasiIndexRouteImport } from './routes/store-admin/_authenticated/nikasi/index'
import { Route as StoreAdminAuthenticatedIncomingIndexRouteImport } from './routes/store-admin/_authenticated/incoming/index'
import { Route as StoreAdminAuthenticatedGroupedIndexRouteImport } from './routes/store-admin/_authenticated/grouped/index'
import { Route as StoreAdminAuthenticatedGradingIndexRouteImport } from './routes/store-admin/_authenticated/grading/index'
import { Route as StoreAdminAuthenticatedDaybookIndexRouteImport } from './routes/store-admin/_authenticated/daybook/index'
import { Route as StoreAdminAuthenticatedAnalyticsIndexRouteImport } from './routes/store-admin/_authenticated/analytics/index'
import { Route as StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport } from './routes/store-admin/_authenticated/people/$farmerStorageLinkId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZustandIndexRoute = ZustandIndexRouteImport.update({
  id: '/zustand/',
  path: '/zustand/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminAuthenticatedRoute = StoreAdminAuthenticatedRouteImport.update({
  id: '/store-admin/_authenticated',
  path: '/store-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminLoginIndexRoute = StoreAdminLoginIndexRouteImport.update({
  id: '/store-admin/login/',
  path: '/store-admin/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminAuthenticatedStorageIndexRoute =
  StoreAdminAuthenticatedStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleIndexRoute =
  StoreAdminAuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedOutgoingIndexRoute =
  StoreAdminAuthenticatedOutgoingIndexRouteImport.update({
    id: '/outgoing/',
    path: '/outgoing/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedNikasiIndexRoute =
  StoreAdminAuthenticatedNikasiIndexRouteImport.update({
    id: '/nikasi/',
    path: '/nikasi/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedIncomingIndexRoute =
  StoreAdminAuthenticatedIncomingIndexRouteImport.update({
    id: '/incoming/',
    path: '/incoming/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedGroupedIndexRoute =
  StoreAdminAuthenticatedGroupedIndexRouteImport.update({
    id: '/grouped/',
    path: '/grouped/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedGradingIndexRoute =
  StoreAdminAuthenticatedGradingIndexRouteImport.update({
    id: '/grading/',
    path: '/grading/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedDaybookIndexRoute =
  StoreAdminAuthenticatedDaybookIndexRouteImport.update({
    id: '/daybook/',
    path: '/daybook/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedAnalyticsIndexRoute =
  StoreAdminAuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute =
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport.update({
    id: '/people/$farmerStorageLinkId/',
    path: '/people/$farmerStorageLinkId/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store-admin': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand/': typeof ZustandIndexRoute
  '/store-admin/login/': typeof StoreAdminLoginIndexRoute
  '/store-admin/analytics/': typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  '/store-admin/daybook/': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/grading/': typeof StoreAdminAuthenticatedGradingIndexRoute
  '/store-admin/grouped/': typeof StoreAdminAuthenticatedGroupedIndexRoute
  '/store-admin/incoming/': typeof StoreAdminAuthenticatedIncomingIndexRoute
  '/store-admin/nikasi/': typeof StoreAdminAuthenticatedNikasiIndexRoute
  '/store-admin/outgoing/': typeof StoreAdminAuthenticatedOutgoingIndexRoute
  '/store-admin/people/': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/storage/': typeof StoreAdminAuthenticatedStorageIndexRoute
  '/store-admin/people/$farmerStorageLinkId/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store-admin': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand': typeof ZustandIndexRoute
  '/store-admin/login': typeof StoreAdminLoginIndexRoute
  '/store-admin/analytics': typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  '/store-admin/daybook': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/grading': typeof StoreAdminAuthenticatedGradingIndexRoute
  '/store-admin/grouped': typeof StoreAdminAuthenticatedGroupedIndexRoute
  '/store-admin/incoming': typeof StoreAdminAuthenticatedIncomingIndexRoute
  '/store-admin/nikasi': typeof StoreAdminAuthenticatedNikasiIndexRoute
  '/store-admin/outgoing': typeof StoreAdminAuthenticatedOutgoingIndexRoute
  '/store-admin/people': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/storage': typeof StoreAdminAuthenticatedStorageIndexRoute
  '/store-admin/people/$farmerStorageLinkId': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/store-admin/_authenticated': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand/': typeof ZustandIndexRoute
  '/store-admin/login/': typeof StoreAdminLoginIndexRoute
  '/store-admin/_authenticated/analytics/': typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  '/store-admin/_authenticated/daybook/': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/_authenticated/grading/': typeof StoreAdminAuthenticatedGradingIndexRoute
  '/store-admin/_authenticated/grouped/': typeof StoreAdminAuthenticatedGroupedIndexRoute
  '/store-admin/_authenticated/incoming/': typeof StoreAdminAuthenticatedIncomingIndexRoute
  '/store-admin/_authenticated/nikasi/': typeof StoreAdminAuthenticatedNikasiIndexRoute
  '/store-admin/_authenticated/outgoing/': typeof StoreAdminAuthenticatedOutgoingIndexRoute
  '/store-admin/_authenticated/people/': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/_authenticated/storage/': typeof StoreAdminAuthenticatedStorageIndexRoute
  '/store-admin/_authenticated/people/$farmerStorageLinkId/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/store-admin'
    | '/zustand/'
    | '/store-admin/login/'
    | '/store-admin/analytics/'
    | '/store-admin/daybook/'
    | '/store-admin/grading/'
    | '/store-admin/grouped/'
    | '/store-admin/incoming/'
    | '/store-admin/nikasi/'
    | '/store-admin/outgoing/'
    | '/store-admin/people/'
    | '/store-admin/storage/'
    | '/store-admin/people/$farmerStorageLinkId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/store-admin'
    | '/zustand'
    | '/store-admin/login'
    | '/store-admin/analytics'
    | '/store-admin/daybook'
    | '/store-admin/grading'
    | '/store-admin/grouped'
    | '/store-admin/incoming'
    | '/store-admin/nikasi'
    | '/store-admin/outgoing'
    | '/store-admin/people'
    | '/store-admin/storage'
    | '/store-admin/people/$farmerStorageLinkId'
  id:
    | '__root__'
    | '/'
    | '/store-admin/_authenticated'
    | '/zustand/'
    | '/store-admin/login/'
    | '/store-admin/_authenticated/analytics/'
    | '/store-admin/_authenticated/daybook/'
    | '/store-admin/_authenticated/grading/'
    | '/store-admin/_authenticated/grouped/'
    | '/store-admin/_authenticated/incoming/'
    | '/store-admin/_authenticated/nikasi/'
    | '/store-admin/_authenticated/outgoing/'
    | '/store-admin/_authenticated/people/'
    | '/store-admin/_authenticated/storage/'
    | '/store-admin/_authenticated/people/$farmerStorageLinkId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreAdminAuthenticatedRoute: typeof StoreAdminAuthenticatedRouteWithChildren
  ZustandIndexRoute: typeof ZustandIndexRoute
  StoreAdminLoginIndexRoute: typeof StoreAdminLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zustand/': {
      id: '/zustand/'
      path: '/zustand'
      fullPath: '/zustand/'
      preLoaderRoute: typeof ZustandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/_authenticated': {
      id: '/store-admin/_authenticated'
      path: '/store-admin'
      fullPath: '/store-admin'
      preLoaderRoute: typeof StoreAdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/login/': {
      id: '/store-admin/login/'
      path: '/store-admin/login'
      fullPath: '/store-admin/login/'
      preLoaderRoute: typeof StoreAdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/_authenticated/storage/': {
      id: '/store-admin/_authenticated/storage/'
      path: '/storage'
      fullPath: '/store-admin/storage/'
      preLoaderRoute: typeof StoreAdminAuthenticatedStorageIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/': {
      id: '/store-admin/_authenticated/people/'
      path: '/people'
      fullPath: '/store-admin/people/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/outgoing/': {
      id: '/store-admin/_authenticated/outgoing/'
      path: '/outgoing'
      fullPath: '/store-admin/outgoing/'
      preLoaderRoute: typeof StoreAdminAuthenticatedOutgoingIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/nikasi/': {
      id: '/store-admin/_authenticated/nikasi/'
      path: '/nikasi'
      fullPath: '/store-admin/nikasi/'
      preLoaderRoute: typeof StoreAdminAuthenticatedNikasiIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/incoming/': {
      id: '/store-admin/_authenticated/incoming/'
      path: '/incoming'
      fullPath: '/store-admin/incoming/'
      preLoaderRoute: typeof StoreAdminAuthenticatedIncomingIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/grouped/': {
      id: '/store-admin/_authenticated/grouped/'
      path: '/grouped'
      fullPath: '/store-admin/grouped/'
      preLoaderRoute: typeof StoreAdminAuthenticatedGroupedIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/grading/': {
      id: '/store-admin/_authenticated/grading/'
      path: '/grading'
      fullPath: '/store-admin/grading/'
      preLoaderRoute: typeof StoreAdminAuthenticatedGradingIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/daybook/': {
      id: '/store-admin/_authenticated/daybook/'
      path: '/daybook'
      fullPath: '/store-admin/daybook/'
      preLoaderRoute: typeof StoreAdminAuthenticatedDaybookIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/analytics/': {
      id: '/store-admin/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/store-admin/analytics/'
      preLoaderRoute: typeof StoreAdminAuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/$farmerStorageLinkId/': {
      id: '/store-admin/_authenticated/people/$farmerStorageLinkId/'
      path: '/people/$farmerStorageLinkId'
      fullPath: '/store-admin/people/$farmerStorageLinkId/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
  }
}

interface StoreAdminAuthenticatedRouteChildren {
  StoreAdminAuthenticatedAnalyticsIndexRoute: typeof StoreAdminAuthenticatedAnalyticsIndexRoute
  StoreAdminAuthenticatedDaybookIndexRoute: typeof StoreAdminAuthenticatedDaybookIndexRoute
  StoreAdminAuthenticatedGradingIndexRoute: typeof StoreAdminAuthenticatedGradingIndexRoute
  StoreAdminAuthenticatedGroupedIndexRoute: typeof StoreAdminAuthenticatedGroupedIndexRoute
  StoreAdminAuthenticatedIncomingIndexRoute: typeof StoreAdminAuthenticatedIncomingIndexRoute
  StoreAdminAuthenticatedNikasiIndexRoute: typeof StoreAdminAuthenticatedNikasiIndexRoute
  StoreAdminAuthenticatedOutgoingIndexRoute: typeof StoreAdminAuthenticatedOutgoingIndexRoute
  StoreAdminAuthenticatedPeopleIndexRoute: typeof StoreAdminAuthenticatedPeopleIndexRoute
  StoreAdminAuthenticatedStorageIndexRoute: typeof StoreAdminAuthenticatedStorageIndexRoute
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}

const StoreAdminAuthenticatedRouteChildren: StoreAdminAuthenticatedRouteChildren =
  {
    StoreAdminAuthenticatedAnalyticsIndexRoute:
      StoreAdminAuthenticatedAnalyticsIndexRoute,
    StoreAdminAuthenticatedDaybookIndexRoute:
      StoreAdminAuthenticatedDaybookIndexRoute,
    StoreAdminAuthenticatedGradingIndexRoute:
      StoreAdminAuthenticatedGradingIndexRoute,
    StoreAdminAuthenticatedGroupedIndexRoute:
      StoreAdminAuthenticatedGroupedIndexRoute,
    StoreAdminAuthenticatedIncomingIndexRoute:
      StoreAdminAuthenticatedIncomingIndexRoute,
    StoreAdminAuthenticatedNikasiIndexRoute:
      StoreAdminAuthenticatedNikasiIndexRoute,
    StoreAdminAuthenticatedOutgoingIndexRoute:
      StoreAdminAuthenticatedOutgoingIndexRoute,
    StoreAdminAuthenticatedPeopleIndexRoute:
      StoreAdminAuthenticatedPeopleIndexRoute,
    StoreAdminAuthenticatedStorageIndexRoute:
      StoreAdminAuthenticatedStorageIndexRoute,
    StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute:
      StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute,
  }

const StoreAdminAuthenticatedRouteWithChildren =
  StoreAdminAuthenticatedRoute._addFileChildren(
    StoreAdminAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreAdminAuthenticatedRoute: StoreAdminAuthenticatedRouteWithChildren,
  ZustandIndexRoute: ZustandIndexRoute,
  StoreAdminLoginIndexRoute: StoreAdminLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
