/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZustandIndexRouteImport } from './routes/zustand/index'
import { Route as StoreAdminAuthenticatedRouteImport } from './routes/store-admin/_authenticated'
import { Route as StoreAdminLoginIndexRouteImport } from './routes/store-admin/login/index'
import { Route as StoreAdminAuthenticatedPeopleIndexRouteImport } from './routes/store-admin/_authenticated/people/index'
import { Route as StoreAdminAuthenticatedDaybookIndexRouteImport } from './routes/store-admin/_authenticated/daybook/index'
import { Route as StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport } from './routes/store-admin/_authenticated/people/$farmerStorageLinkId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZustandIndexRoute = ZustandIndexRouteImport.update({
  id: '/zustand/',
  path: '/zustand/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminAuthenticatedRoute = StoreAdminAuthenticatedRouteImport.update({
  id: '/store-admin/_authenticated',
  path: '/store-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminLoginIndexRoute = StoreAdminLoginIndexRouteImport.update({
  id: '/store-admin/login/',
  path: '/store-admin/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminAuthenticatedPeopleIndexRoute =
  StoreAdminAuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedDaybookIndexRoute =
  StoreAdminAuthenticatedDaybookIndexRouteImport.update({
    id: '/daybook/',
    path: '/daybook/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)
const StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute =
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport.update({
    id: '/people/$farmerStorageLinkId/',
    path: '/people/$farmerStorageLinkId/',
    getParentRoute: () => StoreAdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store-admin': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand/': typeof ZustandIndexRoute
  '/store-admin/login/': typeof StoreAdminLoginIndexRoute
  '/store-admin/daybook/': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/people/': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/people/$farmerStorageLinkId/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store-admin': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand': typeof ZustandIndexRoute
  '/store-admin/login': typeof StoreAdminLoginIndexRoute
  '/store-admin/daybook': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/people': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/people/$farmerStorageLinkId': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/store-admin/_authenticated': typeof StoreAdminAuthenticatedRouteWithChildren
  '/zustand/': typeof ZustandIndexRoute
  '/store-admin/login/': typeof StoreAdminLoginIndexRoute
  '/store-admin/_authenticated/daybook/': typeof StoreAdminAuthenticatedDaybookIndexRoute
  '/store-admin/_authenticated/people/': typeof StoreAdminAuthenticatedPeopleIndexRoute
  '/store-admin/_authenticated/people/$farmerStorageLinkId/': typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/store-admin'
    | '/zustand/'
    | '/store-admin/login/'
    | '/store-admin/daybook/'
    | '/store-admin/people/'
    | '/store-admin/people/$farmerStorageLinkId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/store-admin'
    | '/zustand'
    | '/store-admin/login'
    | '/store-admin/daybook'
    | '/store-admin/people'
    | '/store-admin/people/$farmerStorageLinkId'
  id:
    | '__root__'
    | '/'
    | '/store-admin/_authenticated'
    | '/zustand/'
    | '/store-admin/login/'
    | '/store-admin/_authenticated/daybook/'
    | '/store-admin/_authenticated/people/'
    | '/store-admin/_authenticated/people/$farmerStorageLinkId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreAdminAuthenticatedRoute: typeof StoreAdminAuthenticatedRouteWithChildren
  ZustandIndexRoute: typeof ZustandIndexRoute
  StoreAdminLoginIndexRoute: typeof StoreAdminLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zustand/': {
      id: '/zustand/'
      path: '/zustand'
      fullPath: '/zustand/'
      preLoaderRoute: typeof ZustandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/_authenticated': {
      id: '/store-admin/_authenticated'
      path: '/store-admin'
      fullPath: '/store-admin'
      preLoaderRoute: typeof StoreAdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/login/': {
      id: '/store-admin/login/'
      path: '/store-admin/login'
      fullPath: '/store-admin/login/'
      preLoaderRoute: typeof StoreAdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin/_authenticated/people/': {
      id: '/store-admin/_authenticated/people/'
      path: '/people'
      fullPath: '/store-admin/people/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/daybook/': {
      id: '/store-admin/_authenticated/daybook/'
      path: '/daybook'
      fullPath: '/store-admin/daybook/'
      preLoaderRoute: typeof StoreAdminAuthenticatedDaybookIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
    '/store-admin/_authenticated/people/$farmerStorageLinkId/': {
      id: '/store-admin/_authenticated/people/$farmerStorageLinkId/'
      path: '/people/$farmerStorageLinkId'
      fullPath: '/store-admin/people/$farmerStorageLinkId/'
      preLoaderRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRouteImport
      parentRoute: typeof StoreAdminAuthenticatedRoute
    }
  }
}

interface StoreAdminAuthenticatedRouteChildren {
  StoreAdminAuthenticatedDaybookIndexRoute: typeof StoreAdminAuthenticatedDaybookIndexRoute
  StoreAdminAuthenticatedPeopleIndexRoute: typeof StoreAdminAuthenticatedPeopleIndexRoute
  StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute: typeof StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute
}

const StoreAdminAuthenticatedRouteChildren: StoreAdminAuthenticatedRouteChildren =
  {
    StoreAdminAuthenticatedDaybookIndexRoute:
      StoreAdminAuthenticatedDaybookIndexRoute,
    StoreAdminAuthenticatedPeopleIndexRoute:
      StoreAdminAuthenticatedPeopleIndexRoute,
    StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute:
      StoreAdminAuthenticatedPeopleFarmerStorageLinkIdIndexRoute,
  }

const StoreAdminAuthenticatedRouteWithChildren =
  StoreAdminAuthenticatedRoute._addFileChildren(
    StoreAdminAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreAdminAuthenticatedRoute: StoreAdminAuthenticatedRouteWithChildren,
  ZustandIndexRoute: ZustandIndexRoute,
  StoreAdminLoginIndexRoute: StoreAdminLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
